import Foundation

// Broadcasts shot data to a browser-based sim session via Supabase Realtime.
// Uses only the anon (publishable) key — never the service-role key.
// The session code is generated by the website and typed into the app by the user.
@MainActor
final class LiveSimService: ObservableObject {
    @Published var enteredCode: String = "" {
        didSet {
            let digits = String(enteredCode.filter(\.isNumber).prefix(6))
            if digits != enteredCode { enteredCode = digits; return }
            // Only reset connection state when the actual 6-digit code changes.
            // Avoids double-reset from SwiftUI re-firing didSet on focus changes.
            let prevDigits = String(oldValue.filter(\.isNumber).prefix(6))
            if digits != prevDigits {
                shotsSent = 0
                lastBroadcastError = nil
                isConnectedToSim = false
            }
        }
    }
    @Published private(set) var isBroadcasting = false
    @Published private(set) var isConnectedToSim = false
    @Published private(set) var lastBroadcastError: String?
    @Published private(set) var shotsSent = 0

    private let config: SupabaseConfig?

    init() {
        self.config = SupabaseConfig.load()
    }

    var isReadyToConnect: Bool { enteredCode.count == 6 }

    /// Sends a ping to the website so it advances from the code screen to the course selector.
    func connect() async {
        guard isReadyToConnect else { return }
        await broadcastRaw(event: "ping", payload: [:])
        isConnectedToSim = true
    }

    /// Tells the website which club is currently selected.
    func broadcastClub(_ clubName: String) async {
        guard isConnectedToSim else { return }
        await broadcastRaw(event: "club", payload: ["clubName": clubName])
    }

    func broadcast(metrics: SavedShotMetrics) async {
        guard isReadyToConnect else {
            lastBroadcastError = "Enter the 6-digit code shown on screen"
            return
        }

        isBroadcasting = true
        defer { isBroadcasting = false }

        let payload: [String: Any] = [
            "ballSpeedMph": metrics.ballSpeedMph,
            "carryYards":   metrics.carryYards,
            "totalYards":   metrics.totalYards,
            "vlaDegrees":   metrics.vlaDegrees,
            "backspinRpm":  metrics.backspinRpm,
            "sidespinRpm":  metrics.sidespinRpm,
            "hlaDegrees":   metrics.hlaDegrees,
            "hlaDirection": metrics.sidespinRpm >= 0 ? "right" : "left",
            "smashFactor":  metrics.smashFactor,
        ]

        let ok = await broadcastRaw(event: "shot", payload: payload)
        if ok {
            lastBroadcastError = nil
            shotsSent += 1
        }
    }

    // MARK: - Private

    @discardableResult
    private func broadcastRaw(event: String, payload: [String: Any]) async -> Bool {
        guard let config else { return false }

        let body: [String: Any] = [
            "messages": [[
                "topic":   "tc-sim-\(enteredCode)",
                "event":   event,
                "payload": payload,
            ]],
        ]
        guard let bodyData = try? JSONSerialization.data(withJSONObject: body) else { return false }

        var req = URLRequest(url: config.baseURL.appendingPathComponent("realtime/v1/api/broadcast"))
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue(config.anonKey, forHTTPHeaderField: "apikey")
        let token = UserDefaults.standard.string(forKey: "sb_access_token") ?? config.anonKey
        req.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        req.httpBody = bodyData

        do {
            let (_, response) = try await URLSession.shared.data(for: req)
            if let http = response as? HTTPURLResponse, http.statusCode >= 400 {
                lastBroadcastError = "Broadcast failed (HTTP \(http.statusCode))"
                return false
            }
            return true
        } catch {
            lastBroadcastError = error.localizedDescription
            return false
        }
    }
}
